import 'dart:convert';

import 'package:flutter/material.dart';

class AppLocalizations {
  static const supportedLocales = <Locale>[
    Locale('ru'),
    Locale('en'),
    Locale('es'),
  ];

  static const Map<String, Map<String, String>> _strings = {
    'ru': {
      'menu': 'Меню',
      'playlists': 'Плейлисты',
      'all_songs': 'Все песни',
      'liked_songs': 'Любимые',
      'tracks': 'Треки',
      'logout': 'Выйти',
      'logout_confirm': 'Вы уверены, что хотите выйти?',
      'logged_out': 'Вы вышли из аккаунта',
      'settings': 'Настройки',
      'language': 'Язык',
      'select_language': 'Выберите язык',
      'english': 'English',
      'russian': 'Русский',
      'spanish': 'Español',
      'cancel': 'Отмена',
      'player_tab': 'Плеер',
      'storage_tab': 'Хранилище',
      'guest': 'Гость',
      'no_track_selected': 'Трек не выбран',
      'add_files_storage_hint': 'Добавьте файлы в Хранилище > Локальное',
      'no_local_tracks_yet': 'Локальных треков пока нет',
      'go_storage_add_files': 'Откройте Хранилище и добавьте файлы.',
      'theme_mode': 'Тема',
      'light': 'Светлая',
      'dark': 'Тёмная',
      'accent': 'Акцент',
      'scheme_green': 'Зелёный',
      'scheme_blue': 'Синий',
      'scheme_yellow': 'Жёлтый',
      'scheme_pink': 'Розовый',
      'scheme_purple': 'Фиолетовый',
      'scheme_peach': 'Персиковый',
      'storage_title': 'Хранилище',
      'local': 'Локальное',
      'cloud': 'Облако',
      'upload': 'Загрузить',
      'create_playlist': 'Создать плейлист',
      'search_track': 'Поиск трека',
      'no_cloud_tracks_yet': 'Облачных треков пока нет',
      'cloud_login': 'Вход в облако',
      'cloud_register': 'Регистрация в облаке',
      'cloud_login_hint': 'Войдите, чтобы видеть облачные треки и плейлисты.',
      'cloud_register_hint':
          'Создайте аккаунт для доступа к облачным трекам и плейлистам.',
      'username': 'Имя пользователя',
      'password': 'Пароль',
      'sign_in': 'Войти',
      'create_account': 'Создать аккаунт',
      'already_have_account': 'Уже есть аккаунт? Войти',
      'no_account_register': 'Нет аккаунта? Зарегистрироваться',
      'playlist_name_required': 'Введите название плейлиста',
      'playlist_tracks_required': 'Выберите хотя бы один трек',
      'download': 'Скачать',
      'delete': 'Удалить',
      'download_to_local': 'Скачать в локальное',
      'upload_to_cloud': 'Загрузить в облако',
      'add_to_playlist': 'Добавить в плейлист',
      'upload_tracks': 'Загрузить треки',
      'pick_folder': 'Выбрать папку',
      'auto_scan_device': 'Автопоиск на устройстве',
      'pick_one_or_multiple_audio':
          'Выберите один или несколько аудиофайлов (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'import_from_folder_with_filters':
          'Импорт из папки с фильтрами (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'find_new_audio_on_device': 'Найти новые аудиофайлы на устройстве',
      'cant_access_folder_directly':
          'Нельзя открыть эту папку напрямую на Android. Используйте "Загрузить треки" и выберите файлы.',
      'storage_permission_import_denied':
          'Доступ к хранилищу отклонён. Разрешите доступ для импорта из папки.',
      'no_matching_files_in': 'Нет подходящих файлов в:',
      'imported_files': 'Импортировано файлов:',
      'import_from_folder': 'Импорт из папки',
      'auto_scan_android_only': 'Автопоиск пока работает только на Android',
      'storage_permission_scan_denied':
          'Доступ к хранилищу отклонён. Разрешите доступ для сканирования.',
      'scanning_device_audio': 'Сканирование устройства на аудиофайлы...',
      'no_new_audio_files': 'Новых аудиофайлов не найдено',
      'added_files': 'Добавлено файлов:',
      'found_new_audio_files': 'Найдено новых аудиофайлов:',
      'select_all': 'Выбрать все',
      'clear': 'Очистить',
      'selected_shown': 'выбрано • показано',
      'search_by_name_or_path': 'Поиск по имени файла или пути',
      'add_selected_files': 'Добавить выбранные файлы',
      'create_playlist_title': 'Создать плейлист',
      'playlist_name': 'Название плейлиста',
      'select_tracks': 'Выберите треки',
      'clear_selection': 'Снять выделение',
      'add_local_tracks_first': 'Сначала добавьте локальные треки',
    },
    'en': {
      'menu': 'Menu',
      'playlists': 'Playlists',
      'all_songs': 'All songs',
      'liked_songs': 'Liked songs',
      'tracks': 'Tracks',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'logged_out': 'Logged out',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select language',
      'english': 'English',
      'russian': 'Russian',
      'spanish': 'Spanish',
      'cancel': 'Cancel',
      'player_tab': 'Player',
      'storage_tab': 'Storage',
      'guest': 'Guest',
      'no_track_selected': 'No track selected',
      'add_files_storage_hint': 'Add files in Storage > Local',
      'no_local_tracks_yet': 'No local tracks yet',
      'go_storage_add_files': 'Go to Storage tab and add files.',
      'theme_mode': 'Theme mode',
      'light': 'Light',
      'dark': 'Dark',
      'accent': 'Accent',
      'scheme_green': 'Green',
      'scheme_blue': 'Blue',
      'scheme_yellow': 'Yellow',
      'scheme_pink': 'Pink',
      'scheme_purple': 'Purple',
      'scheme_peach': 'Peach',
      'storage_title': 'Storage',
      'local': 'Local',
      'cloud': 'Cloud',
      'upload': 'Upload',
      'create_playlist': 'Create playlist',
      'search_track': 'Search track',
      'no_cloud_tracks_yet': 'No cloud tracks yet',
      'cloud_login': 'Cloud login',
      'cloud_register': 'Cloud registration',
      'cloud_login_hint': 'Sign in to view cloud playlists and tracks.',
      'cloud_register_hint':
          'Create account to access cloud playlists and tracks.',
      'username': 'Username',
      'password': 'Password',
      'sign_in': 'Sign in',
      'create_account': 'Create account',
      'already_have_account': 'Already have account? Sign in',
      'no_account_register': 'No account? Register',
      'playlist_name_required': 'Enter playlist name',
      'playlist_tracks_required': 'Select at least one track',
      'download': 'Download',
      'delete': 'Delete',
      'download_to_local': 'Download to local',
      'upload_to_cloud': 'Upload to cloud',
      'add_to_playlist': 'Add to playlist',
      'upload_tracks': 'Upload tracks',
      'pick_folder': 'Pick folder',
      'auto_scan_device': 'Auto scan device',
      'pick_one_or_multiple_audio':
          'Pick one or multiple audio files (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'import_from_folder_with_filters':
          'Import files from folder with filters (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'find_new_audio_on_device': 'Find new audio files on device',
      'cant_access_folder_directly':
          'Can not access this folder directly on Android. Use "Upload tracks" and select files.',
      'storage_permission_import_denied':
          'Storage permission denied. Grant permission to import from folder.',
      'no_matching_files_in': 'No matching files in:',
      'imported_files': 'Imported files:',
      'import_from_folder': 'Import from folder',
      'auto_scan_android_only':
          'Auto scan is currently supported on Android only',
      'storage_permission_scan_denied':
          'Storage permission denied. Grant permission to scan.',
      'scanning_device_audio': 'Scanning device for audio files...',
      'no_new_audio_files': 'No new audio files found',
      'added_files': 'Added files:',
      'found_new_audio_files': 'Found new audio files:',
      'select_all': 'Select all',
      'clear': 'Clear',
      'selected_shown': 'selected • shown',
      'search_by_name_or_path': 'Search by file name or path',
      'add_selected_files': 'Add selected files',
      'create_playlist_title': 'Create playlist',
      'playlist_name': 'Playlist name',
      'select_tracks': 'Select tracks',
      'clear_selection': 'Clear selection',
      'add_local_tracks_first': 'Add local tracks first',
    },
    'es': {
      'menu': 'Menú',
      'playlists': 'Listas',
      'all_songs': 'Todas las canciones',
      'liked_songs': 'Me gusta',
      'tracks': 'Pistas',
      'logout': 'Cerrar sesión',
      'logout_confirm': '¿Seguro que quieres cerrar sesión?',
      'logged_out': 'Sesión cerrada',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'select_language': 'Selecciona el idioma',
      'english': 'English',
      'russian': 'Русский',
      'spanish': 'Español',
      'cancel': 'Cancelar',
      'player_tab': 'Reproductor',
      'storage_tab': 'Almacenamiento',
      'guest': 'Invitado',
      'no_track_selected': 'Ninguna pista seleccionada',
      'add_files_storage_hint': 'Agrega archivos en Almacenamiento > Local',
      'no_local_tracks_yet': 'Aún no hay pistas locales',
      'go_storage_add_files': 'Ve a Almacenamiento y agrega archivos.',
      'theme_mode': 'Modo de tema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'accent': 'Acento',
      'scheme_green': 'Verde',
      'scheme_blue': 'Azul',
      'scheme_yellow': 'Amarillo',
      'scheme_pink': 'Rosa',
      'scheme_purple': 'Morado',
      'scheme_peach': 'Melocotón',
      'storage_title': 'Almacenamiento',
      'local': 'Local',
      'cloud': 'Nube',
      'upload': 'Subir',
      'create_playlist': 'Crear lista',
      'search_track': 'Buscar pista',
      'no_cloud_tracks_yet': 'Aún no hay pistas en la nube',
      'cloud_login': 'Inicio de sesión en la nube',
      'cloud_register': 'Registro en la nube',
      'cloud_login_hint': 'Inicia sesión para ver pistas y listas en la nube.',
      'cloud_register_hint':
          'Crea una cuenta para acceder a pistas y listas en la nube.',
      'username': 'Nombre de usuario',
      'password': 'Contraseña',
      'sign_in': 'Entrar',
      'create_account': 'Crear cuenta',
      'already_have_account': '¿Ya tienes cuenta? Entrar',
      'no_account_register': '¿Sin cuenta? Regístrate',
      'playlist_name_required': 'Introduce el nombre de la lista',
      'playlist_tracks_required': 'Selecciona al menos una pista',
      'download': 'Descargar',
      'delete': 'Eliminar',
      'download_to_local': 'Descargar a local',
      'upload_to_cloud': 'Subir a la nube',
      'add_to_playlist': 'Añadir a la lista',
      'upload_tracks': 'Subir pistas',
      'pick_folder': 'Elegir carpeta',
      'auto_scan_device': 'Búsqueda automática',
      'pick_one_or_multiple_audio':
          'Elige uno o varios archivos de audio (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'import_from_folder_with_filters':
          'Importar desde carpeta con filtros (MP3, WAV, FLAC, M4A/MP4, AAC, OGG, OPUS)',
      'find_new_audio_on_device': 'Buscar nuevos audios en el dispositivo',
      'cant_access_folder_directly':
          'No se puede acceder a esta carpeta directamente en Android. Usa "Subir pistas" y elige archivos.',
      'storage_permission_import_denied':
          'Permiso de almacenamiento denegado. Concédelo para importar.',
      'no_matching_files_in': 'No hay archivos válidos en:',
      'imported_files': 'Archivos importados:',
      'import_from_folder': 'Importar desde carpeta',
      'auto_scan_android_only':
          'La búsqueda automática está disponible solo en Android',
      'storage_permission_scan_denied':
          'Permiso de almacenamiento denegado. Concédelo para escanear.',
      'scanning_device_audio': 'Escaneando el dispositivo en busca de audio...',
      'no_new_audio_files': 'No se encontraron archivos nuevos de audio',
      'added_files': 'Archivos añadidos:',
      'found_new_audio_files': 'Nuevos archivos de audio encontrados:',
      'select_all': 'Seleccionar todo',
      'clear': 'Limpiar',
      'selected_shown': 'seleccionados • visibles',
      'search_by_name_or_path': 'Buscar por nombre o ruta',
      'add_selected_files': 'Agregar archivos seleccionados',
      'create_playlist_title': 'Crear playlist',
      'playlist_name': 'Nombre de la playlist',
      'select_tracks': 'Selecciona pistas',
      'clear_selection': 'Quitar selección',
      'add_local_tracks_first': 'Primero añade pistas locales',
    },
  };

  static String text(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final byLocale = _strings[code] ?? _strings['en']!;
    final raw = byLocale[key] ?? _strings['en']![key] ?? key;
    return _decodeMojibakeIfNeeded(raw);
  }

  static String _decodeMojibakeIfNeeded(String input) {
    if (!input.contains('Р') && !input.contains('Г') && !input.contains('В')) {
      return input;
    }
    try {
      return utf8.decode(latin1.encode(input));
    } catch (_) {
      return input;
    }
  }
}
