# Официальный образ Go на базе Debian (стабильнее для разработки)
FROM golang:1.25

# Установка Air (хот-релоад для Go)
RUN go install github.com/air-verse/air@latest

# Рабочая директория
WORKDIR /app

# Копирование зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копирование исходного кода
COPY . .

# Экспозиция порта
EXPOSE 8080

# Запуск с хот-релоадом
CMD ["air"]